### ISSUE TITLE
Update Instagram Law Enforcement Guidelines filters

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/services-all#224]
https://github.com/ambanum/OpenTermsArchive-versions/commit/748f84cae23565a32bcbfa1b447ea2632689c3a4

**Comment by martinratinaud** [comment]
@MattiSG unfortunately from what I can see this must have been a transient error.

When I reissue the scraping, data gathered is correctly cleaned by selectors.

The thing is that at one point in time (which is the snapshot you're refering to)
The structure was slightly different (see screenshot below compared to https://help.instagram.com/494561080557017)
![Screen Shot 2021-12-06 at 11 37 43](https://user-images.githubusercontent.com/4191809/144806357-928af1d6-4099-43ef-9dd3-0746534e8d22.png)

I also believe it has not been reupdated yet because of Github issue creation problem which make the core reboot before reaching Instagram (and which should be fixed in [this PR](https://github.com/ambanum/OpenTermsArchive/pull/717))

So I will close this issue as soon as a new version will have been gathered with the previous data

**Comment by MattiSG** [comment]
Thanks for having investigated 👍 Crazy that they would have a temporary rewrite of the whole page structure! 😯

**Comment by martinratinaud** [comment]
Indeed

Or it'as a matter of load balancer giving the new page on 1% of the traffic

**Comment by martinratinaud** [comment]
Version is now ok https://github.com/ambanum/OpenTermsArchive-versions/commit/291f02e3c9ea0b6bedf552389e7d310a984ac34f#diff-a1a5329e2d415267fe10742adfa1f0a8d9c6cb67c9acb288f0ace59065d3ed93

Closing
